// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
)

type Game struct {
	ID        int64
	Name      sql.NullString
	Path      sql.NullString
	UpdatedAt sql.NullString
}

type PlaySession struct {
	ID          int64
	GameID      sql.NullInt64
	StartTime   sql.NullString
	EndTime     sql.NullString
	ForceClosed sql.NullInt64
	Invalid     sql.NullInt64
}
