// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
)

type Game struct {
	ID        int64
	Name      sql.NullString
	SystemTag sql.NullString
	Path      sql.NullString
	ImagePath sql.NullString
	CreatedAt sql.NullString
	UpdatedAt sql.NullString
}

type PlaySession struct {
	ID        int64
	GameID    sql.NullInt64
	StartTime sql.NullString
	EndTime   sql.NullString
	Playtime  sql.NullInt64
}
